import "./globals.css"

import { Open_Sans, Sevillana } from "next/font/google"

const open_sans = Open_Sans({
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={open_sans.className}>{children}</body>
    </html>
  )
}
